baseURL = "https://mattnet.de/"
languageCode = "de-de"
defaultContentLanguage = "de"
title = "Mattnet"
theme = "hallo"

[Author]
    name = "Matthias"

[params]
    [params.colors]
        background = "#ffc43c"
        foreground = "#edf7ff"
        hover = "#0f0e0a"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/schnapsidee"
    [[params.links]] 
        iconset = "fas"        
	icon = "envelope"
        title = "E-mail"
        url = "mailto:mail@mattnet.de"
    [[params.links]]
        icon = "linkedin"
        title = "Linked In"
        url = "https://linkedin.com/in/matthiasmai"
