name: Build and Deploy

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo theme
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.117.0'

      - name: Build
        run: hugo --minify

      - name: deploy to webserver
        run: rsync --delete -rvzh ./public/ deploy@mattnet.de:/usr/share/nginx/html/mattnet.de/
